#stack to manually add the conscia roles to an account.

AWSTemplateFormatVersion: '2010-09-09'
Description: Billing, Admin and ReadOnly roles for conscia employees.
Resources:
  ConsciaBillingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: conscia-billing      
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::055524301700:root
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
            Sid: ''
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/Billing
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess

  ConsciaAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: conscia-admin
      MaxSessionDuration: 7200
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::055524301700:root
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
            Sid: ''
        Version: '2012-10-17'
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ConsciaReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: conscia-readonly
      MaxSessionDuration: 7200
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::055524301700:root
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
            Sid: ''
        Version: '2012-10-17'
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

  ConsciaCloudmanager:
    Type: AWS::IAM::Role
    Properties:
      RoleName: conscia-cloudmanager     
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::454464851268:root
            Condition:
              StringEquals:
               sts:ExternalId: a9cfbe77a810dcd920410f496685ef 
            Sid: ''
        Version: '2012-10-17'
      Path: "/"
      ManagedPolicyArns:
        - !Ref consciaCloudHealthPolicy

  ConsciaCloudHealthPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: cloudhealth-policy    
      PolicyDocument:
        Version: '2012-10-17' 
        Statement:
          - Effect: Allow
            Action:
            - autoscaling:Describe*
            - aws-portal:ViewBilling
            - aws-portal:ViewUsage
            - cloudformation:ListStacks
            - cloudformation:ListStackResources
            - cloudformation:DescribeStacks
            - cloudformation:DescribeStackEvents
            - cloudformation:DescribeStackResources
            - cloudformation:GetTemplate
            - cloudfront:Get*
            - cloudfront:List*
            - cloudtrail:DescribeTrails
            - cloudtrail:GetEventSelectors
            - cloudtrail:ListTags
            - cloudwatch:Describe*
            - cloudwatch:Get*
            - cloudwatch:List*
            - config:Get*
            - config:Describe*
            - config:Deliver*
            - config:List*
            - cur:Describe*
            - dms:Describe*
            - dms:List*
            - dynamodb:DescribeTable
            - dynamodb:List*
            - ec2:Describe*
            - ec2:GetReservedInstancesExchangeQuote
            - ecs:List*
            - ecs:Describe*
            - elasticache:Describe*
            - elasticache:ListTagsForResource
            - elasticbeanstalk:Check*
            - elasticbeanstalk:Describe*
            - elasticbeanstalk:List*
            - elasticbeanstalk:RequestEnvironmentInfo
            - elasticbeanstalk:RetrieveEnvironmentInfo
            - elasticfilesystem:Describe*
            - elasticloadbalancing:Describe*
            - elasticmapreduce:Describe*
            - elasticmapreduce:List*
            - es:List*
            - es:Describe*
            - firehose:ListDeliveryStreams
            - firehose:DescribeDeliveryStream
            - iam:List*
            - iam:Get*
            - iam:GenerateCredentialReport
            - kinesis:Describe*
            - kinesis:List*
            - kms:DescribeKey
            - kms:GetKeyRotationStatus
            - kms:ListKeys
            - lambda:List*
            - logs:Describe*
            - organizations:ListAccounts
            - organizations:ListTagsForResource
            - organizations:DescribeOrganization
            - redshift:Describe*
            - route53:Get*
            - route53:List*
            - rds:Describe*
            - rds:ListTagsForResource
            - s3:GetBucketAcl
            - s3:GetBucketLocation
            - s3:GetBucketLogging
            - s3:GetBucketPolicyStatus
            - s3:GetBucketPublicAccessBlock
            - s3:GetAccountPublicAccessBlock
            - s3:GetBucketTagging
            - s3:GetBucketVersioning
            - s3:GetBucketWebsite
            - s3:List*
            - sagemaker:Describe*
            - sagemaker:List*
            - savingsplans:DescribeSavingsPlans
            - sdb:GetAttributes
            - sdb:List*
            - ses:Get*
            - ses:List*
            - sns:Get*
            - sns:List*
            - sqs:GetQueueAttributes
            - sqs:ListQueues
            - storagegateway:List*
            - storagegateway:Describe*
            - workspaces:Describe*
            Resource: "*"
                                  